name: play_audio
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0-384.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.3
  audioplayers: 4.0.0
  path_provider:
  motion_toast: 2.7.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/bubbling1.wav
